version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports: ["8080:8080"]
    depends_on: [redis]
  worker:
    build:
      context: .
    # You can comment-out worker for now; keep it ready for later
      dockerfile: Dockerfile.worker
    env_file: .env
    depends_on: [redis]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]