services:
  frontend:
    image: node:dev
    container_name: node-frontend
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command:
      - bash
      - -lc
      - |
        set -e
        cd /app
        if [ -f package-lock.json ]; then npm ci; else npm install; fi
        npm run dev -- --host 0.0.0.0 --port 5173
